server:
  port: 80
spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      server-addr: ..
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-system
          uri: lb://service-system
          predicates:
            - Path=/sys/**